version: "3.4"

services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin:/var/lib/pgadmin
  postgres:
    restart: always
    build: ./
    container_name: "postgres_container"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wildfire
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wildfire
    volumes:
      - pgvol:/var/lib/postgresql/data

volumes:
  pgvol:
  pgadmin:
